services:
  app:
    container_name: go_auth_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_PORT: 9300
      JWT_SECRET: blockchain890!
      JWT_EXPIRE_MINUTES: 720
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: jwtauth
      DB_PASSWORD: secret123!
      DB_NAME: ginauth
    ports:
      - "9300:9300"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: jwtauth
      POSTGRES_PASSWORD: secret123!
      POSTGRES_DB: ginauth
    ports:
      - "5437:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
